name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Connect to PostgreSQL
        run: pwd && ls -l
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432